name: pre-commit
description: run pre-commit

runs:
  using: composite
  steps:
  - run: python -m pip install pre-commit
    shell: bash
  - run: python -m pip freeze --local
    shell: bash
  - uses: actions/cache@v4
    with:
      path: ~/.cache/pre-commit
      key: pre-commit-3|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}
  - run: pre-commit run --show-diff-on-failure --color=always --all-files -- > pre-commit.out 2>&1
    shell: bash

  - name: Set output
    if: always()
    id: output
    shell: bash
    run: |
      tr '`' "'" < pre-commit.out > output_sanitized.txt
      {
        echo 'stdout<<EOF'
        cat output_sanitized.txt
        echo EOF
      } >> $GITHUB_OUTPUT

  - name: check pre-commit checks
    if: always()
    uses: actions/github-script@v7
    with:
      script: |
        const text = `${{ steps.output.outputs.stdout }}`
        github.rest.issues.createComment({
          issue_number: context.issue.number,
          owner: context.repo.owner,
          repo: context.repo.repo,
          body: `Content of the file: \n${text}`
        });