name: pre-commit
description: run pre-commit

runs:
  using: composite
  steps:
  - run: python -m pip install pre-commit
    shell: bash
  - run: python -m pip freeze --local
    shell: bash
  - run: pre-commit run --color=never --all-files > pre-commit.out
    shell: bash

  - name: Install terraform docs
    run: |
      curl -sSLo ./terraform-docs.tar.gz https://terraform-docs.io/dl/v0.19.0/terraform-docs-v0.19.0-$(uname)-amd64.tar.gz
      tar -xzf terraform-docs.tar.gz
      chmod +x terraform-docs
      mv terraform-docs $PATH/terraform-docs
    shell: bash

  - name: check pre-commit checks
    if: always()
    uses: actions/github-script@v7
    with:
      script: |
        const fs = require('fs');
        const fileContent = fs.readFileSync('pre-commit.out', 'utf8');
        
        github.rest.issues.createComment({
          issue_number: context.issue.number,
          owner: context.repo.owner,
          repo: context.repo.repo,
          body: `<details><summary>Pre-commit Checks</summary>

          ~~~
          ${ fileContent }
          ~~~

          </details>`
        });