name: pre-commit
description: run pre-commit

runs:
  using: composite
  steps:
  - run: |
      pip install pre-commit --root-user-action=ignore
    shell: bash

  - name: Install terraform-docs
    run: |
      mkdir -p .bin
      curl -sSLo ./terraform-docs.tar.gz https://terraform-docs.io/dl/v0.19.0/terraform-docs-v0.19.0-$(uname)-amd64.tar.gz
      tar -xzf terraform-docs.tar.gz
      chmod +x terraform-docs
      mv terraform-docs .bin/
      echo "$PWD/.bin" >> $GITHUB_PATH
    shell: bash

  - name: Execute pre-commit Checks
    run: |
      echo "$(pre-commit run --color=never --all-files)" | tee pre-commit.out
    shell: bash

  - name: Output pre-commit checks
    if: always()
    uses: actions/github-script@v7
    with:
      script: |
        const fs = require('fs');
        let fileContent = "";
        try {
          fileContent = fs.readFileSync('pre-commit.out', 'utf8');
        }
        catch (error) {
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: "There was an error reading the pre-commit file, please check actions logs"
          });
        }
        github.rest.issues.createComment({
          issue_number: context.issue.number,
          owner: context.repo.owner,
          repo: context.repo.repo,
          body: `<details><summary>Pre-commit Checks</summary>

          ~~~
          ${ fileContent }
          ~~~

          </details>`
        });
