name: main_update
run-name: >-
  ${{ github.event.issue.number && format('pre_commit | PR-{0}', github.event.issue.number)
  || 'pre-commit Branch Update' }}

permissions: read-all

on:
  pull_request:
    types: [opened, synchronize]
    branches: main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pipeline:
    runs-on: ubuntu-latest
    name: linting
    permissions: write-all

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.issue.pull_request && format('refs/pull/{0}/head', github.event.issue.number) || '' }}
          fetch-depth: 0

      - name: Basic Linting
        uses: TRI-IE/pre-commit-checks@main
